### ISSUE TITLE
Uses the latest FFmpeg release n4.0-39-gda39990

### ISSUE THREAD

**Issue by nzackoya** [bravobit/FFmpeg-Android#41] opened 2018-06-20 16:12 UTC
I updated to this library after using ffmpeg-android-java, but the version of the ffmpeg is still 3.0.1, and not 4.0 or even 3.4. Is there anything I need to setup?

**Comment by Sub6Resources** [comment] 2018-06-20 16:31
Are you sure you are calling this library and not ffmpeg-android-java?

**Comment by Brianvdb** [comment] 2018-06-21 07:57
Duplicate of: #40

The library is using FFmpeg 4.0.

**Closed by Brianvdb** 2018-06-21 07:57 UTC
Labels: duplicate

**Comment by nzackoya** [comment] 2018-06-21 10:50
@Sub6Resources I removed ffmpeg-android-java, cleaned the project, rebuilt, and run again. But ssill it is 3.0.1. Should I do anything else?

**Comment by Sub6Resources** [comment] 2018-06-21 13:22
@nzackoya Try uninstalling or clearing data for your app on the emulator/device and running again. Perhaps the old binary is still there.
