### ISSUE TITLE
Remove FFprobe, to reduce APK?

### ISSUE THREAD

**Issue by formatBCE** [bravobit/FFmpeg-Android#43] opened 2018-06-25 13:08 UTC
Could you please give some highlights of removing FFprobe? It significantly raises APK size, and i don't need it in my project. Should i fork it, or maybe, you have separate build?

**Comment by Brianvdb** [comment] 2018-06-25 13:12
Duplicate of #20 

You can find this in the WIKI: [https://github.com/bravobit/FFmpeg-Android/wiki/Reduce-APK-File-Size](https://github.com/bravobit/FFmpeg-Android/wiki/Reduce-APK-File-Size)

**Closed by Brianvdb** 2018-06-25 13:12 UTC
Labels: duplicate, question
