### ISSUE TITLE
the bag is too large，can it be smaller?

### ISSUE THREAD

**Issue by XinYiWorld** [bravobit/FFmpeg-Android#152] opened 2020-03-21 10:48 UTC
the sum size of ffmpeg and ffprobe in one cpu platform is about 37MB，it's too large for an apk file。

**Comment by nirmalcirklestudio** [comment] 2020-04-22 05:41
Duplicate of #80

**Comment by XinYiWorld** [comment] 2020-04-22 05:48
Thanks，I'll try it!

**Closed as completed** 2020-04-22 05:48 UTC
