### ISSUE TITLE
[Question] What did you do to solve 

### ISSUE THREAD

**Issue by bolds07** [bravobit/FFmpeg-Android#39] opened 2018-06-08 16:21 UTC
I'm having the same problem with `CANNOT LINK EXECUTABLE ffmpeg: has text relocations` would you mind to share what did you to fix the problem?

Which compiler parameters did you use and which ffmpeg configuration...

thanks

**Comment by Brianvdb** [comment] 2018-06-08 16:46
Duplicate of #33

**Closed by Brianvdb** 2018-06-08 16:46 UTC
Labels: duplicate, question
